spring:
  application:
    name: spring-dubbo-provider

server:
  port:8080

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    id: ${spring.application.name}
  scan:
    basePackages: tech.zg.springboot.dubbo.provider.service
  provider:
    timeout: 1000